/* Copyright 2020 QMK
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was auto-generated by:
 *    `qmk chibios-confupdate -i keyboards/tkw/grandiceps/mcuconf.h -r platforms/chibios/BLACKPILL_STM32_F411/configs/mcuconf.h`
 */

#pragma once

#include_next "mcuconf.h"

#undef STM32_I2C_USE_I2C1
#define STM32_I2C_USE_I2C1 TRUE

#undef STM32_I2C_I2C1_RX_DMA_STREAM
#define STM32_I2C_I2C1_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 0)
//#undef STM32_I2C_I2C1_TX_DMA_STREAM
//#define STM32_I2C_I2C1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 1)

//////
// #undef STM32_PWM_USE_TIM2
// #define STM32_PWM_USE_TIM2 TRUE

// #undef STM32_PWM_USE_TIM3
// #define STM32_PWM_USE_TIM3 TRUE

// #undef STM32_SPI_USE_SPI1
// #define STM32_SPI_USE_SPI1           TRUE

// #undef STM32_SPI_SPI1_RX_DMA_STREAM
// #define STM32_SPI_SPI1_RX_DMA_STREAM STM32_DMA_STREAM_ID(2, 0)
// #undef STM32_SPI_SPI1_TX_DMA_STREAM
// #define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(2, 3)

// #undef STM32_SERIAL_USE_USART2
// #define STM32_SERIAL_USE_USART2 TRUE
//////

// #undef STM32_UART_USART2_RX_DMA_STREAM
// #define STM32_UART_USART2_RX_DMA_STREAM STM32_DMA_STREAM_ID(1, 5)
// #undef STM32_UART_USART2_TX_DMA_STREAM
// #define STM32_UART_USART2_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 6)

//////
// #undef STM32_GPT_USE_TIM4
// #define STM32_GPT_USE_TIM4 TRUE

// #undef STM32_ST_USE_TIMER
// #define STM32_ST_USE_TIMER 5


// #undef STM32_PLLM_VALUE
// #undef STM32_PLLN_VALUE
// #undef STM32_PLLP_VALUE
// #undef STM32_PLLQ_VALUE
// #undef STM32_PPRE1
// #undef STM32_PPRE2


// //STABLE use when crystals is 8mhz
// #define STM32_PLLM_VALUE                    8
// #define STM32_PLLN_VALUE                    192
// #define STM32_PLLP_VALUE                    2
// #define STM32_PLLQ_VALUE                    4
// #define STM32_PPRE1                         STM32_PPRE1_DIV2 //4
// #define STM32_PPRE2                         STM32_PPRE2_DIV1 //2
//////

//Also works when the crystal is 8mhz
// #define STM32_PLLM_VALUE                    8
// #define STM32_PLLN_VALUE                    384
// #define STM32_PLLP_VALUE                    4
// #define STM32_PLLQ_VALUE                    8
// #define STM32_PPRE1                         STM32_PPRE1_DIV4
// #define STM32_PPRE2                         STM32_PPRE2_DIV4